### PR TITLE
New local dependency objects and new version of ToolBase

### PR DESCRIPTION
**Pull request by alexander-yevsyukov**
This PR updates `buildSrc` introducing sub-package for internal Spine dependencies. ToolBase was bumped to `2.0.0-SNAPSHOT.232`.

### CODE REVIEW

**Comment by alexander-yevsyukov** [comment]
@armiol, I have to turn it back to draft because Windows build fails (again) because of this error:

```
> Process 'command 'C:\hostedtoolcache\windows\Java_Zulu_jdk\11.0.25-9\x64\bin\java.exe'' could not be started because the command line exceed operating system limits.
```

**Comment by alexander-yevsyukov** [comment]
@armiol,
> I have to turn it back to draft because Windows build fails (again) because of this error:

IntelliJ Platform dependencies are now [back in the command line](https://github.com/SpineEventEngine/ProtoData/actions/runs/11534437960/job/32108442966?pr=281).

**Comment by armiol** [comment]
@alexander-yevsyukov I think it is because these original Gradle projects have all the dependencies. And Gradle publishes the `.module` and `.pom` files from the original "small" JAR.

**Comment by alexander-yevsyukov** [comment]
> @alexander-yevsyukov I think it is because these original Gradle projects have all the dependencies. And Gradle publishes the `.module` and `.pom` files from the original "small" JAR.

I found the cause. I left the dependencies to the IJ Platform in `build.gradle.kts` in `psi-java`. There was the dependency on `intellij-platform-java` and direct dependencies. Have a loot it in this [PR draft](https://github.com/SpineEventEngine/tool-base/pull/107). But, there is something strange about the current layout of dependencies: not all of them are resolved in the Kotlin code under `psi-java`. I'm going to dig into shortly today. Going to the office.

**Review by armiol — APPROVED** [review]

**Pull request merged**
